// SPIKE (throwaway) — provenance test: fal Seedream v5 lite still → fal Seedance 2.0 fast i2v.
// Andrew's claim: Seedance does NOT block a photoreal teacher when the image was generated by
// Seedream itself. Replicate-Seedream → Replicate/fal-Seedance blocked twice (E005/422); this
// tests the tightest available "generated by itself" pair: same vendor, same host.
//
// Run:  cd ~/aivideostudio-backend && npx tsx src/scripts/spikeTeacherFalPair.ts
// env:  FAL_KEY
// cost: ~$0.40

import 'dotenv/config';
import { fal } from '@fal-ai/client';
import { mkdirSync, writeFileSync } from 'node:fs';

const OUT = `${process.env.HOME}/Downloads/spike-teacher-dreamina`;
const SEEDREAM_FAL = 'bytedance/seedream/v5/lite/text-to-image';
const SEEDANCE_FAL = 'bytedance/seedance-2.0/fast/image-to-video';

fal.config({ credentials: process.env.FAL_KEY });

const PHRASE = 'la manzana — apple';
const SPOKEN = 'Hola. Today\'s word is manzana. Manzana means apple. Repeat after me: manzana.';
const STILL = 'Photorealistic friendly female Spanish teacher in her 30s standing in the '
  + 'left third of the frame, warm smile, facing camera. To her right, occupying the right '
  + 'two-thirds of the frame: a white whiteboard flat on the wall, parallel to the image plane, '
  + 'shot straight-on (NOT angled). Bright modern classroom, soft daylight, vertical 9:16. '
  + `On the upper area of the board, in neat teacher handwriting, black dry-erase marker, is `
  + `written exactly this text: "${PHRASE}". No other text anywhere.`;
const ANIMATE = 'A friendly Spanish teacher speaks directly to the camera in a calm, '
  + 'clear teaching voice. She says these exact words and NOTHING else — no greeting beyond the '
  + `script, no added sentences, no improvised lines, no words after the last one: "${SPOKEN}". `
  + 'The spoken audio must match this line verbatim.';

async function main(): Promise<void> {
  mkdirSync(OUT, { recursive: true });

  console.log('1. fal Seedream v5 lite still…');
  const img = (await fal.subscribe(SEEDREAM_FAL, {
    input: { prompt: STILL, aspect_ratio: '9:16' } as Record<string, unknown> as never,
  })) as { data?: { images?: { url?: string }[] } };
  const stillUrl = img.data?.images?.[0]?.url;
  if (!stillUrl) throw new Error(`no image url in ${JSON.stringify(img.data).slice(0, 300)}`);
  const ir = await fetch(stillUrl);
  writeFileSync(`${OUT}/still_C_fal_seedream.png`, Buffer.from(await ir.arrayBuffer()));
  console.log('   still saved → still_C_fal_seedream.png');

  console.log('2. fal Seedance 2.0 fast i2v on that still…');
  try {
    const res = (await fal.subscribe(SEEDANCE_FAL, {
      input: {
        image_url: stillUrl,
        prompt: ANIMATE,
        duration: 6,
        resolution: '720p',
        aspect_ratio: '9:16',
        generate_audio: true,
      } as Record<string, unknown> as never,
    })) as { data?: { video?: { url?: string } } };
    const v = res.data?.video?.url;
    if (!v) throw new Error(`no video url in ${JSON.stringify(res.data).slice(0, 400)}`);
    const r = await fetch(v);
    writeFileSync(`${OUT}/teacher_C_falpair.mp4`, Buffer.from(await r.arrayBuffer()));
    console.log(`PASS — same-host Seedream→Seedance accepted: ${OUT}/teacher_C_falpair.mp4\nurl: ${v}`);
  } catch (e) {
    console.log(`BLOCKED/FAILED — ${String((e as Error)?.message ?? e).slice(0, 400)}`);
    process.exit(1);
  }
}

main();
