-- Studio filters (per-timeline-range color grading) foundation migration.
-- Additive + re-runnable (CREATE ... IF NOT EXISTS / ADD COLUMN IF NOT EXISTS throughout).
--
-- ⚠️ Migrations here are MANUAL: creating this file does NOT apply it. A human must run it
-- against the database Railway actually serves and then trigger a deploy.
--
-- ⚠️ DO NOT apply this through the local .env DATABASE_URL. As of 2026-07-28 .env points at the
-- Neon DEV branch (ep-rough-wildflower) while prod is a DIFFERENT branch (ep-noisy-bonus) with
-- DIFFERENT data. Read the real target with `railway variables` first — a migration "applied to
-- prod" via .env once broke prod for hours.
--
-- STATUS: NOT YET APPLIED.

-- ─── project_filters ──────────────────────────────────────────────────────────
-- A filter is a timeline OBJECT, not a clip property. It covers an arbitrary
-- [start_offset_seconds, start_offset_seconds + duration_seconds) window on the project
-- timeline, so one filter can span several clips, cover part of a single clip, or stack with
-- other filters over the same moment.
--
-- No media, therefore no r2_key and no trim window — a filter is a pure color lookup applied to
-- whatever frames sit underneath it. filter_id names a LUT in assets/luts (generated by
-- scripts/generate-filter-luts.mjs). The SAME id resolves to the SAME .cube file in the iOS
-- bundle, which is what keeps the on-device preview, the on-device export, and this server's
-- ffmpeg compose in agreement about what "Noir" looks like.
--
-- z_index is the stack order where filters overlap in time (the pill's "Layers" control): lower
-- renders first, so a higher z_index grades on top of the result beneath it.
--
-- Soft-delete mirrors project_clips (Plan 13-21 B1) so the editor's undo can restore a deleted
-- filter by id. Every read path MUST filter deleted_at IS NULL.

CREATE TABLE IF NOT EXISTS project_filters (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id),
  filter_id text NOT NULL,
  intensity double precision NOT NULL DEFAULT 1,
  start_offset_seconds double precision NOT NULL DEFAULT 0,
  duration_seconds double precision NOT NULL,
  z_index integer NOT NULL DEFAULT 0,
  deleted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Re-runnable guards, in case an earlier partial run created the table without these.
ALTER TABLE project_filters ADD COLUMN IF NOT EXISTS intensity double precision NOT NULL DEFAULT 1;
ALTER TABLE project_filters ADD COLUMN IF NOT EXISTS z_index integer NOT NULL DEFAULT 0;
ALTER TABLE project_filters ADD COLUMN IF NOT EXISTS deleted_at timestamptz;

-- Every read is "the live filters for this project", same shape as project_clips' access pattern.
CREATE INDEX IF NOT EXISTS project_filters_project_id_idx ON project_filters(project_id);
